# Generated by Django 3.2.7 on 2021-09-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='video_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
